---
- name: addressUpdate
  #hosts: 'localhost'
  hosts: routers
  strategy: free
  connection: local
  gather_facts: false
  vars_prompt:
#    - name: hostIP
#      prompt: Host to execute on
#      private: false
    - name: un
      prompt: Router Username
      default: admin
      private: false
    - name: pw
      prompt: Router Password
      private: true
    - name: addressList
      prompt: Address List to Update
      default: fulladmin
      private: false

  module_defaults:
          group/community.routeros.api:
            hostname: '{{ inventory_hostname }}' #change to {{ hostIP }} to manually select and uncomment lines 9-11
            username: "{{ un }}"
            password: "{{ pw }}"


  tasks:
    - name: Set up address list
      community.routeros.api_modify:
        path: ip firewall address-list
        handle_absent_entries: ignore
        handle_entries_content: ignore
        data:
          - list: "{{ addressList }}"
            address: 20.221.112.37
            comment: "Sonar v2 Egress"
          - list: "{{ addressList }}"
            address: 20.221.114.13
            comment: "Sonar v2 Egress"
          - list: "{{ addressList }}"
            address: 52.158.209.86
            comment: "Sonar v2 Egress"
            

